embedding_size: 64
feat_embed_dim: 64
 
n_layers: [1, 2, 3]
#una run alla volta per ogni n_layers
dropout: [0, 0.2, 0.5]
reg_weight: [1e-04, 1e-03, 1e-02, 1e-01]
cl_weight: [0.1, 0.5, 1, 2]
 
use_neg_sampling: False
 
hyper_parameters: ["n_layers", "reg_weight", "dropout", "cl_weight"]